
echo "INITIALISING THE VPBC SECURITY PROTOCOL..."

echo "STARTING  RANDOM SPLITTING SEQUENCE"
echo "10%"
echo "80%"
echo "100%"

python3 rsg_fm.py

echo "ENTER THE SPLITS GENERATED IN EACH TRANSACTION"
